### ISSUE TITLE
Rename our custom Qbs-enabled branch to master and rename upstream branches accordingly

### ISSUE THREAD

**Issue by johnbivens** [Proemion/SortFilterProxyModel#2]
In order to allow us to do things like this within our repositories...:

```
git submodule foreach git checkout master && \
git submodule foreach git pull origin master
```

...it would be great if the Qbs-enabled branch we are actively using (currently `feature/filters-and-sorters`) could be the `master` branch within this fork. The upstream `master` could be renamed to something like `master_upstream`.

What do you think, @saidinesh5?

**Comment by saidinesh5** [comment]
Aye. Done.
