### ISSUE TITLE
Use appropriate Q_DECL_IMPORT/Q_DECL_EXPORT macros for exported symbols

### ISSUE THREAD

**Issue by johnbivens** [Proemion/SortFilterProxyModel#4]
I haven't tested a Windows build of this code yet, but I would expect it to fail. The problem is, Windows DLLs really need the `dllimport` and `dllexport` stuff when building. If they're not used appropriately, the builds will fail.

Have a look at the other code within our libraries - this is the reason for the "export" headers in each repository, which are responsible for using the correct macro based on whether or not it's a library build or the library is being used/linked externally.

See this page for more information: https://doc.qt.io/qt-5/sharedlibrary.html

**Comment by johnbivens** [comment]
@saidinesh5 Please don't forget this, we'll need it for the Windows version of PROedit. I'm pretty sure, anyway - I can't imagine this works as-is (as mentioned in this issue's description).

**Comment by saidinesh5** [comment]
@johnbivens Would the windows build need this still, if we were directly linking the library? (or using --no-as-needed) .

But Yeah, I will add this as we are moving to loading this as a plugin

**Comment by johnbivens** [comment]
@saidinesh5 yep, as far as I know. It has to do with how Windows loads shared object libraries (in this case DLLs), and it needs to know what is imported (from a shared object library) or exported (within a shared object library) at compile time.
